# coding=utf-8

# 项目负责人: HanWen_lu (hanwen517@foxmail.com)
#            DogeBoy2 (dogeboy2@outlook.com)
# 反馈: support@hroton.cn

# 版本: 1.0.0  内部版本号: demo-25130
# Build: 2025-1-30 12:16

# Form implementation generated from reading ui file '.\Main.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

# © 2025 HrotonStudio. All rights reserved.

from PyQt6 import QtCore, QtGui, QtWidgets
import sys
from functools import partial
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(590, 360)
        MainWindow.setWindowOpacity(1.0)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.LaunchButton = PrimaryPushButton(parent=self.centralwidget)
        self.LaunchButton.setGeometry(QtCore.QRect(450, 300, 130, 50))
        self.LaunchButton.setObjectName("LaunchButton")
        self.VerticalSeparator = VerticalSeparator(parent=self.centralwidget)
        self.VerticalSeparator.setGeometry(QtCore.QRect(310, 10, 3, 320))
        self.VerticalSeparator.setObjectName("VerticalSeparator")
        self.SettingTitle = StrongBodyLabel(parent=self.centralwidget)
        self.SettingTitle.setGeometry(QtCore.QRect(340, 20, 120, 20))
        self.CloseButton = PushButton(parent=self.centralwidget)
        self.CloseButton.setGeometry(QtCore.QRect(560,0,30,30))
        self.CloseButton.clicked.connect(lambda:CloseBtn_on_Clicked()) # 关闭按钮信号
        def CloseBtn_on_Clicked():   # 关闭按钮
            sys.exit(0)              # 退出程序
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.SettingTitle.setFont(font)
        self.SettingTitle.setObjectName("SettingTitle")
        self.MaxMemLabel = CaptionLabel(parent=self.centralwidget)
        self.MaxMemLabel.setGeometry(QtCore.QRect(350, 85, 70, 15))
        self.MaxMemLabel.setObjectName("MaxMemLabel")
        self.CaptionLabel_2 = CaptionLabel(parent=self.centralwidget)
        self.CaptionLabel_2.setGeometry(QtCore.QRect(485, 85, 70, 15))
        self.CaptionLabel_2.setObjectName("CaptionLabel_2")
        self.MemTitle = BodyLabel(parent=self.centralwidget)
        self.MemTitle.setGeometry(QtCore.QRect(345, 55, 65, 20))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.MemTitle.setFont(font)
        self.MemTitle.setObjectName("MemTitle")
        self.MaxMemText = LineEdit(parent=self.centralwidget)
        self.MaxMemText.setGeometry(QtCore.QRect(420, 85, 60, 20))
        self.MaxMemText.setMinimumSize(QtCore.QSize(0, 20))
        self.MaxMemText.setMaximumSize(QtCore.QSize(16777215, 20))
        self.MaxMemText.setObjectName("MaxMemText")
        self.MinMemLabel = CaptionLabel(parent=self.centralwidget)
        self.MinMemLabel.setGeometry(QtCore.QRect(350, 110, 70, 16))
        self.MinMemLabel.setObjectName("MinMemLabel")
        self.CaptionLabel_4 = CaptionLabel(parent=self.centralwidget)
        self.CaptionLabel_4.setGeometry(QtCore.QRect(485, 110, 70, 15))
        self.CaptionLabel_4.setObjectName("CaptionLabel_4")
        self.MinMemText = LineEdit(parent=self.centralwidget)
        self.MinMemText.setGeometry(QtCore.QRect(420, 110, 60, 20))
        self.MinMemText.setMinimumSize(QtCore.QSize(0, 20))
        self.MinMemText.setMaximumSize(QtCore.QSize(16777215, 20))
        self.MinMemText.setObjectName("MinMemText")
        self.VerticalSeparator_2 = VerticalSeparator(parent=self.centralwidget)
        self.VerticalSeparator_2.setGeometry(QtCore.QRect(340, 80, 3, 61))
        self.VerticalSeparator_2.setObjectName("VerticalSeparator_2")
        self.HorizontalSeparator = HorizontalSeparator(parent=self.centralwidget)
        self.HorizontalSeparator.setGeometry(QtCore.QRect(340, 140, 190, 3))
        self.HorizontalSeparator.setObjectName("HorizontalSeparator")
        self.VerticalSeparator_3 = VerticalSeparator(parent=self.centralwidget)
        self.VerticalSeparator_3.setGeometry(QtCore.QRect(530, 65, 3, 75))
        self.VerticalSeparator_3.setObjectName("VerticalSeparator_3")
        self.HorizontalSeparator_2 = HorizontalSeparator(parent=self.centralwidget)
        self.HorizontalSeparator_2.setGeometry(QtCore.QRect(415, 65, 115, 3))
        self.HorizontalSeparator_2.setObjectName("HorizontalSeparator_2")
        self.JVMText = TextEdit(parent=self.centralwidget)
        self.JVMText.setGeometry(QtCore.QRect(340, 175, 190, 100))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.JVMText.sizePolicy().hasHeightForWidth())
        self.JVMText.setSizePolicy(sizePolicy)
        self.JVMText.setMinimumSize(QtCore.QSize(190, 100))
        self.JVMText.setObjectName("JVMText")
        self.JVMSettingTitle = StrongBodyLabel(parent=self.centralwidget)
        self.JVMSettingTitle.setGeometry(QtCore.QRect(340, 150, 115, 19))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.JVMSettingTitle.setFont(font)
        self.JVMSettingTitle.setObjectName("JVMSettingTitle")
        self.CoreVersionList = ListWidget(parent=self.centralwidget)
        self.CoreVersionList.setGeometry(QtCore.QRect(30, 60, 255, 250))
        self.CoreVersionList.setObjectName("CoreVersionList")
        stands = [
            'Spigot-1.21.jar','Spigot-1.21.4.jar','Paper-1.21.jar','Paper-1.21.1.jar','Paper-1.21.4.jar','Vanilla-1.21.jar','Vanilla-1.21.1.jar','Vanilla-1.21.4.jar'
            ]
        for stand in stands:
            item = QtWidgets.QListWidgetItem(stand)
            self.CoreVersionList.addItem(item)

        self.CoreListTitle = StrongBodyLabel(parent=self.centralwidget)
        self.CoreListTitle.setGeometry(QtCore.QRect(30, 20, 140, 20))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.CoreListTitle.setFont(font)
        self.CoreListTitle.setObjectName("CoreListTitle")

        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.retranslateUi(MainWindow)
        self.CoreVersionList.itemClicked.connect(self.on_core_version_selected)
    def on_core_version_selected(self, current):
        if  current is not None:
            CoreFileNameJar = current.text()
            print(CoreFileNameJar)
            
            try:
                max_mem = int(self.MaxMemText.text())
                min_mem = int(self.MinMemText.text())
                self.LaunchButton.clicked.connect(partial(StartServer, max_mem, min_mem, CoreFileNameJar))
            except ValueError:
                print("内存设置必须为整数!")

        else:
            CoreFileNameJar = ""
            print("错误! 未选择服务端版本!")
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Demo"))
        self.LaunchButton.setText(_translate("MainWindow", "开服"))
        self.SettingTitle.setText(_translate("MainWindow", "参数设置"))
        self.MaxMemLabel.setText(_translate("MainWindow", "最大内存："))
        self.CaptionLabel_2.setText(_translate("MainWindow", "MB"))
        self.MemTitle.setText(_translate("MainWindow", "内存设置"))
        self.MaxMemText.setText(_translate("MainWindow", ""))
        self.MinMemLabel.setText(_translate("MainWindow", "最小内存："))
        self.CaptionLabel_4.setText(_translate("MainWindow", "MB"))
        self.MinMemText.setText(_translate("MainWindow", ""))
        self.JVMSettingTitle.setText(_translate("MainWindow", "JVM设置"))
        self.CoreListTitle.setText(_translate("MainWindow", "服务端版本选择"))
        self.CloseButton.setText(_translate("MainWindow","×"))
    

class ConsoleWindow(QtWidgets.QDialog):
    def __init__(self, parent=None):
        super(ConsoleWindow, self).__init__(parent)
        self.text_browser = QtWidgets.QTextBrowser(self)
        layout = QtWidgets.QVBoxLayout(self)
        layout.addWidget(self.text_browser)
        self.setLayout(layout)
    
    def write(self, text):
        self.text_browser.append(text)
    
    def flush(self):
        pass

# 重定向 stdout 和 stderr
def redirect_output(console_window):
    sys.stdout = console_window
    sys.stderr = console_window

# 修改 StartServer 函数以使用新的 ConsoleWindow
def StartServer(MaximumMemory, MinimumMemory, CoreFileNameJar:str):
    # 创建并显示控制台窗口
    MaximumMemory = str(MaximumMemory)
    MinimumMemory = str(MinimumMemory)
    print(MaximumMemory)
    print(MinimumMemory)
    print(type(MaximumMemory))
    print(type(MinimumMemory))
    
    try:
        console_window = ConsoleWindow()
        console_window.show()
        redirect_output(console_window)
        # MaximumMemory = int(Ui_MainWindow.MaxMemText.text())
        # MinimumMemory = int(Ui_MainWindow.MinMemText.text())
        
        # 开服命令整合
        # command = f"java -Xmx{MaximumMemory}M -Xms{MinimumMemory}M -jar {CoreFileName}.jar -Dcom.mojang.eula.agree=true"
        # CoreFileNameJar = CoreFileName + ".jar"
        if not os.path.isfile(CoreFileNameJar):
            raise FileNotFoundError(f"指定的 JAR 文件未找到: {CoreFileNameJar}")
        
        # 使用 subprocess.Popen 代替 os.system 以实现实时输出重定向
        os.system("java -version")

        process = QtCore.QProcess()
        process.setProgram("java")
        process.setArguments(["-Xmx%sM" % MaximumMemory,"-Xms%sM" % MinimumMemory,"-jar", CoreFileNameJar])
        process.readyReadStandardOutput.connect(lambda: console_window.text_browser.append(process.readAllStandardOutput().data().decode()))
        process.readyReadStandardError.connect(lambda: console_window.text_browser.append(process.readAllStandardError().data().decode()))
        process.start()
    except Exception as e:
        console_window.text_browser.append(f"启动服务器发生了错误: {e}")

from qfluentwidgets import (BodyLabel, CaptionLabel, HorizontalSeparator, LineEdit, NavigationBar, PrimaryPushButton, StrongBodyLabel, TextEdit, VerticalSeparator,ListWidget,PushButton
    )
import os